name: Deploy to GitHub Pages

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          # cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Create .env config file
        run: cp example.env .env

      - name: Build website
        run: npm run build && cp -r build github-pages

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: github-pages

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: ${{  github.ref_name == github.event.repository.default_branch }}

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        